
services:
  db:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Expose DB port to host for easier debugging
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todos"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: todo-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5013:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment to Development
      - ConnectionStrings__TodosDb=Host=db;Port=5432;Database=todos;Username=admin;Password=password
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # For local development, the browser needs to talk to the API via the host machine's port.
        # We map port 5013 on the host to the api container's port 8080.
        VITE_REACT_APP_API_URL: http://localhost:5013
    restart: always
    ports:
      - "5173:80" # Map host port 5173 to container port 80 (Nginx default)
    depends_on:
      - api

volumes:
  postgres-data: