
services:
  db:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432" # Expose DB port to host for easier debugging
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: todo-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5013:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development  # Set the environment to Development
      - ConnectionStrings__TodosDb=Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # This variable will be substituted into the nginx.conf.template for local development.
      - API_URL=http://api
    restart: always
    ports:
      - "5173:80" # Map host port 5173 to container port 80 (Nginx default)
    depends_on:
      - api

volumes:
  postgres-data: