apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: frontend
          # IMPORTANT: Replace this with your actual image path from GHCR
          image: ghcr.io/wedgehov/todo-frontend:1.0.0
          ports:
            # Assuming your production frontend image serves on port 80
            - containerPort: 80
          # The frontend needs to know where the backend API is.
          # How you use this depends on your frontend setup.
          env:
            - name: VITE_REACT_APP_API_URL
              # This will point to the Ingress, not the internal service
              value: "https://todo-app.10.1.8.174.nip.io:31003"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80